### ISSUE TITLE
CJS requires don't work when bundled by ESM package

### ISSUE THREAD

**Issue by zvictor** [zvictor/faugra#28]
Running tsup with the `--format cjs` option fails with an error for files importing `faugra`, but only when bundling from an ESM package (i.e. `"type": "module"`):

```haskell
TypeError: (0 , import_faugra.default) is not a function
    at main (/faugra/examples/modularized/build/index.cjs:21:52)
    at Object.<anonymous> (/faugra/examples/modularized/build/index.cjs:32:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

Running `tsup index.ts --format cjs` in our [basic example](https://github.com/zvictor/faugra/tree/master/examples/basic) (CJS) works, but running it in the [modularized example](https://github.com/zvictor/faugra/tree/master/examples/modularized) (ESM) fails.

My statements are verifiable by automated tests:
* [working case](https://github.com/zvictor/faugra/blob/2a20a7307fb8d4f98c8d93c0988e54d0be9a200a/tests/specs/build-sdk.js#L198-L215)
* [failing case](https://github.com/zvictor/faugra/blob/2a20a7307fb8d4f98c8d93c0988e54d0be9a200a/tests/specs/build-sdk.js#L300-L322) (please uncomment those lines before running)

These 2 issues seem to be related to it:
* https://github.com/evanw/esbuild/issues/1856
* https://github.com/evanw/esbuild/issues/2023

**Manually editing the bundled file and replacing `__toESM(require("faugra"), 1)` by `__toESM(require("faugra"), 0)` fix the issue.**

**Comment by zvictor** [comment]
This might be a workaround in some situations: https://github.com/TypeStrong/ts-node/issues/935#issuecomment-913179458
