### ISSUE TITLE
Send "incomplete" schemas to fauna (not expanded)

### ISSUE THREAD

**Issue by zvictor** [zvictor/faugra#9]
_Note: this issue is similar to #1, but here we just want to push the schema to fauna (not pulling it back afterwards)._

---

Fauna expands our schemas and automatically adds mutations and input types ([source](https://docs.fauna.com/fauna/current/api/graphql/input#naming-considerations)):

> The FaunaDB GraphQL API automatically creates input types for user-defined types. For example, when you create a `User` type, the input type `UserInput` is automatically created for you. The FaunaDB GraphQL API also automatically creates the mutations `createUser` and `updateUser`, both of this use the auto-created `UserInput` input type.

Faugra uses @graphql-tools/import to allow modularisation of the schema, but it is not aware of the fauna's behaviour. Thus, if you try to refer to any of the "still to be created inputs", an error will be thrown:

```haskell
Error: Couldn't find type FileStorageInput in any of the schemas.
    at visitFile (/myapp/node_modules/@graphql-tools/import/index.cjs.js:245:31)
    at processImport (/myapp/node_modules/@graphql-tools/import/index.cjs.js:31:17)
    at FaugraSchemaLoader.handleFileContent (/myapp/node_modules/faugra/utils.js:126:24)
    at FaugraSchemaLoader.load (/myapp/node_modules/@graphql-tools/graphql-file-loader/index.cjs.js:788:21)
    at async loadFile (/myapp/node_modules/@graphql-tools/load/index.cjs.js:48:24)
    at async /myapp/@graphql-tools/load/index.cjs.js:425:24
```

One workaround for this is to manually be copying and pasting the auto generated code by fauna into my schemas, and then run faugra again. Apparently, everything works fine at first, as Fauna doesn't complain when **an auto generated input gets replaced by another with identical content**. However, I noticed that [Relational mutations](https://docs.fauna.com/fauna/current/api/graphql/relations#mutations) stop working. **Manually defining a [___Relation](https://docs.fauna.com/fauna/current/api/graphql/relations) input breaks all the mutations that use that input.**

Thus, one cannot use Faugra with schemas that use [GraphQL relations](https://docs.fauna.com/fauna/current/api/graphql/relations). 😞

**Comment by zvictor** [comment]
I thought for a while and realised that I was trying to force graphql-tools to do something it was not designed for. For the use case presented here, we better just concatenate all the schema files and push the result as it is to faunadb instead of using graphql-tools to merge all the files.

Fixed in https://github.com/zvictor/faugra/commit/d4e7f9de25b46c2bb2e4f2fc22d07f6189bec602.
